config/routes.rb
DmixSite::Application.routes.draw do
	devise_for :usuarios, :path => "usuarios", :path_names => { :sign_in => 'entrar', :sign_out => 'sair', :password => 'senha', :confirmation => 'verificacao', :unlock => 'desbloquear', :registration => 'registrar', :sign_up => 'criar' }

	resources :projetos
	root :to=>"inicial#index"
end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
	attr_accessible :nome, :descricao
	belongs_to :usuario
	validates :usuario_id, :presence=>true
	validates :nome, :presence=>true
	validates :descricao, :presence=>true
	def to_s
		nome
	end
	
	def dono
		return self.usuario
	end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :last_name
  def to_s
		"#{name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inicial_controller.rb
class InicialController < ApplicationController
  def index
  end

end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
	before_filter :authenticate_usuario!
	respond_to :html, :json
	
  def index
    @projetos = Projeto.all
		respond_with(@projetos)
  end

  def show
    @projeto = Projeto.find(params[:id])
		respond_with(@projeto)
  end

  def new

    @projeto = Projeto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @projeto }
    end
  end

  def edit
    @projeto = Projeto.find(params[:id])
  end

  def create
    @projeto = Projeto.new(params[:projeto])
		@projeto.usuario_id = current_usuario.id
    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'projeto foi criado com sucesso.' }
        format.json { render json: @projeto, status: :created, location: @projeto }
      else
        format.html { render action: "new" }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projetos/1
  # PUT /projetos/1.json
  def update
    @projeto = Projeto.find(params[:id])
		@projeto.usuario_id = current_usuario.id

    respond_to do |format|
      if @projeto.update_attributes(params[:projeto])
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @projeto = Projeto.find(params[:id])
    @projeto.destroy

    respond_to do |format|
      format.html { redirect_to projetos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicial_helper.rb
module InicialHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/inicial/index.html.erb
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Tc Full Integration</h1>
        <p>Tc é uma plataforma que simplifica o entendimento entre o dono do projeto e os desenvolvedores.</p>
        <p><a class="btn btn-primary btn-large">Leia mais &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Gerenciamento Ágil</h2>
           <p>TcFI é uma ferramenta de gerenciamento de projeto de acordo com as metodologias ágeis mais atuais do mercado. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Integrados teste</h2>
           <p>TcFI possui ferramentas para integrar os testes funcionais da aplicação ao códigos RoR garantindo mais segurança aos stackholders.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TcFi</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "TcFi", root_url, :class=>"brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Projetos", projetos_path  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
                <li><%= link_to "Entrar", new_usuario_session_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
              <%= yield %>
           
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/projetos/_form.html.erb
<%= form_for(@projeto) do |f| %>
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit "Criar Projeto" %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<h1>Editing projeto</h1>

<%= render 'form' %>

<%= link_to 'Show', @projeto %> |
<%= link_to 'Back', projetos_path %>

app/views/projetos/index.html.erb
<h1>Listing projetos</h1>
<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Usuario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projetos.each do |projeto| %>
  <tr>
    <td><%= projeto.nome %></td>
    <td><%= projeto.descricao %></td>
    <td><%= projeto.usuario_id %></td>
    <td><%= link_to 'Show', projeto %></td>
    <td><%= link_to 'Edit', edit_projeto_path(projeto) %></td>
    <td><%= link_to 'Destroy', projeto, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Projeto', new_projeto_path %>

app/views/projetos/new.html.erb
<h1>New projeto</h1>

<%= render 'form' %>

<%= link_to 'Back', projetos_path %>

app/views/projetos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @projeto.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @projeto.descricao %>
</p>

<p>
  <b>Criado por:</b> <%= @projeto.dono %>
</p>


<%= link_to 'Edit', edit_projeto_path(@projeto) %> |
<%= link_to 'Back', projetos_path %>

app/views/usuarios/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>